server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery: 
        locator:
          enabled: true
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuario/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: carro-service
          uri: lb://carro-service
          predicates:
            - Path=/carro/**
        - id: bicicleta-service
          uri: lb://bicicleta-service
          predicates:
            - Path=/bicicleta/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8180/auth/realms/tutorial-realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8180/auth/realms/tutorial-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8180/auth/realms/tutorial-realm/protocol/openid-connect/token
        registration:
          tutorial-client:
            provider: keycloak
            client-id: tutorial-client
            client-secret: d29b9dfe-a258-403d-8d32-0f5dac5a47bc
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/tutorial-client"