server:
  port: 8081
spring:
  cloud: 
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/ChristianRaulRamirez/microservices-tutorial
          search-paths: congif-data
  application:
    name: config-service